# Generated by Django 4.0.1 on 2022-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_field',
            field=models.ImageField(upload_to='static'),
        ),
    ]
